language: java
jdk: oraclejdk8
after_success: "./.travis.after_success.sh"
sudo: required
dist: trusty
branches:
  only:
  - V13
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository/com/vaadin
env:
  global:
  - secure: heyhCYKpIOXyqzjE88LnKI14tLlmmDsrXXfw1TZL6pQUGZ3ZEeNYf/DgPaqQ5X3D3Pv8WAps1fpoqQyvHiDz1PHZdeQyw5Lxq7Z0DKV19VvPtdABdTW7YWeSmZ+ogAYsa+ZWnPdZIrVwK8tyHwGnGiD3zqeTNoDpH6yfU2weBVUpSI2fUZoRPJDYMQDn7KBdl3PqM3kDVfGLzEXeNVPLTraXu5iyr/cBAtbohMDyv2vw4XE7QWI32kDjnxDVuY+nil7JHxvBrtvvpPJRyLhPZUzxmFT41A3EzuAjDwdKPBQULC+W7v2glTQeyyrIll+GWyXErnpJu2WGRo96nUf5wtG79W4bS5U2moTDB5jFuOEQ+MXAEPWVadnkEh/zL1DovJNX3/kAU6FwLUNP/Lks9tORWSyGfHbYgGv36Scgm7MR+FIR3902+i1rKfG1w9c3lTv4bwNyB41EJ9Qfy1JBLFNW7fEvDKWAw/CQEhcCmvZPMQrEsepboJogZeeX2C62pJWoinD5OX5b1x1GLDzhtug4k1gzSD4F/2hNmoAAVw+6tQ1TJVPHZSegu1h/klIkn+hluzeyTWU84kVQZyUGCCsyaMYDRdTXrU3ISdazGQpkDLIP3vjzQa19UUWNhm5zNVlPnQQ9YWt39nmj7NO2ysJwuxWgWB97aVLsXc/qVHI=
  - secure: NyFLh/ek6UJ2znwIF8m27m9W0O9+t/+ZADW/3S0GncQdIZidpOik539IVlq8KHgINTgWwEHgQFuD5fXR93mtJo3wqVSED7KSdni3wr5sThTULVY4QUR2nbS1aHTodxrSsz1C5COaxuAq/mjwBf+gnIPUOUf76zCHYiOKGHM29q7Y+nFo8ZsSRbNXpKBvbltvNu2qhblecHIcZWIPasl5HT745hqt9eWWkH0FY8YnRKnUdImmnjQ6FV5XHRcm2RyUka9Dh9RVsmsndia+y8I6JInTWDx31FGDpXWV83gEV6vvoHqgRqUt8JxqMiUk0F5hxRjglBhWAfpm2NaqvTze6J/I/AWp0I21HSULFp4kS5zCZ72okt1dKlA5EuwNIRcS23MY10v7449fuqxfQxMWy6el4oxxibZStzIXE3Lb4fMu+XMN2XxhdwHkT9S0uhVQWOaw6pe/ax7mnRX1aOdnQzmF8lT2pncJ0MtkbC5TiBbjvAdT2grE3zc74ELSMT/IWPIG7GX64R41W4U8cG4HpWaK30Uip4MPvIphIBIVMnOCZwwaYVxLZGaeP1dLuGUKjPdMNneyXVIYM8F367tCiPa4CK5yCR+0PjIvqneRWoomPvo1cFSUK6A+YwXw3QAY/1O7YTIPP1HXuuWZjOKWijaFPJLSBSbQDUTnrtnxfHU=
